version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"    # RabbitMQ server
      - "15672:15672"  # Management interface
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network

  fastapi_app:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - app_network

  celery_worker:
    build: .
    volumes:
      - .:/code
    command: celery -A src.worker worker --loglevel=info
    depends_on:
      - rabbitmq
      - fastapi_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  rabbitmq_data:
